In [6]:
import pandas as pd
import numpy as np
import os

En primer lugar, ejecutamos el main.py de extracción de datos, para actualizar mantener los datos actualizados

In [7]:
actualizar = input("""¿Deseas actualizar los archivos de datos? (s/n)
         Ten en cuenta que puede tardar bastante en hacer las consultas, 
         por lo que si ya has cargado los datos una vez recomiendo no volver a hacerlo: """)

if actualizar=="s":
    %run main.py
elif actualizar=="n":
    print("No se han actualizado los archivos de datos.")

No se han actualizado los archivos de datos.

In [15]:
localidades = pd.read_csv('data/processed/flujo_ine_localidad.csv', sep=',', encoding='UTF-8')
provincias = pd.read_csv('data/processed/flujo_ine_provincia.csv', sep=',', encoding='UTF-8')
localidades_data = pd.read_csv('data/processed/localidades.csv', sep=',', encoding='UTF-8')
OpenStreetDf = pd.read_csv('data/processed/oferta_osm.csv', sep=',', encoding='UTF-8')
provincias_data = pd.read_csv('data/processed/municipios_espana.csv', sep=',', encoding='UTF-8')

In [ ]:
localidades.head()

,INE_EOH_MUN.punto_turistico,INE_EOH_MUN.indicador,INE_EOH_MUN.residencia,INE_EOH_MUN.nombre_serie_completo,INE_EOH_MUN.cod_serie,INE_EOH_MUN.anio,INE_EOH_MUN.periodo,INE_EOH_MUN.valor,INE_EOH_MUN.fuente,INE_EOH_MUN.tabla_id,_meta.fecha_extraccion
0,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,19464.0,INE_EOH_MUN,2078,2026-08-16T19:44:33.809177
1,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,20574.0,INE_EOH_MUN,2078,2026-08-16T19:44:33.809177
2,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,21012.0,INE_EOH_MUN,2078,2026-08-16T19:44:33.809177
3,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,20189.0,INE_EOH_MUN,2078,2026-08-16T19:44:33.809177
4,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,18573.0,INE_EOH_MUN,2078,2026-08-16T19:44:33.809177

In [17]:
localidades_data.head()

,CartoCiudad.cod_ine,CartoCiudad.nombre_municipio,CartoCiudad.provincia,CartoCiudad.ccaa,CartoCiudad.latitud,CartoCiudad.longitud,_meta.fuente_geocod,_meta.fecha_extraccion,_meta.cod_ine_clave,_meta.nombre_municipio
0,1059,Vitoria-Gasteiz,Araba/Álava,País Vasco/Euskadi,42.850584,-2.661450,CartoCiudad+IGN,2026-08-16T19:44:35.129466,1059,Vitoria-Gasteiz
1,2003,Albacete,Albacete,Castilla-La Mancha,38.995092,-1.855915,CartoCiudad+IGN,2026-08-16T19:44:36.904845,2003,Albacete
2,3014,Alacant/Alicante,Alacant/Alicante,Comunitat Valenciana,38.343637,-0.488171,CartoCiudad+IGN,2026-08-16T19:44:38.906531,3014,Alicante
3,4013,Almería,Almería,Andalucía,36.868574,-2.312028,CartoCiudad+IGN,2026-08-16T19:44:40.906180,4013,Almería
4,5019,Ávila,Ávila,Castilla y León,40.657195,-4.662668,CartoCiudad+IGN,2026-08-16T19:44:42.907876,5019,Ávila

In [20]:
provincias[provincias['INE_EOH_PROV.indicador']=='Viajero'].head()

,INE_EOH_PROV.ambito,INE_EOH_PROV.indicador,INE_EOH_PROV.residencia,INE_EOH_PROV.nombre_serie_completo,INE_EOH_PROV.cod_serie,INE_EOH_PROV.anio,INE_EOH_PROV.periodo,INE_EOH_PROV.valor,INE_EOH_PROV.fuente,INE_EOH_PROV.tabla_id,_meta.fecha_extraccion
1080,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,206637.0,INE_EOH_PROV,2074,2026-08-16T19:44:32.732199
1081,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,175443.0,INE_EOH_PROV,2074,2026-08-16T19:44:32.732199
1082,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,147543.0,INE_EOH_PROV,2074,2026-08-16T19:44:32.732199
1083,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,113361.0,INE_EOH_PROV,2074,2026-08-16T19:44:32.732199
1084,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,87964.0,INE_EOH_PROV,2074,2026-08-16T19:44:32.732199

In [21]:
provincias_data.head()

,INE_Pob_MUN.nombre_municipio,INE_Pob_MUN.poblacion_oficial,INE_Pob_MUN.anio,INE_Pob_MUN.cod_serie,INE_Pob_MUN.nombre_serie_completo,INE_Pob_MUN.fuente,_meta.fecha_extraccion
0,Ababuj,73.0,2025,DPOP19723,Ababuj. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-16T19:44:32.394536
1,Abades,849.0,2025,DPOP17671,Abades. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-16T19:44:32.394536
2,Abadía,337.0,2025,DPOP4663,Abadía. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-16T19:44:32.394536
3,Abadín,2239.0,2025,DPOP12721,Abadín. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-16T19:44:32.394536
4,Abadiño,7768.0,2025,DPOP22525,Abadiño. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-16T19:44:32.394536

In [22]:
OpenStreetDf.head()

,OSM_Overpass.num_hoteles,OSM_Overpass.num_restaurantes,OSM_Overpass.num_atracciones,OSM_Overpass.num_museos,OSM_Overpass.fuente,OSM_Overpass.fecha_extraccion,_meta.cod_ine_clave,_meta.nombre_municipio
0,32,50,0,16,OSM_Nominatim_Fallback,2026-08-16T19:46:33.417363,1059,Vitoria-Gasteiz
1,50,50,0,29,OSM_Nominatim_Fallback,2026-08-16T19:46:49.876119,2003,Albacete
2,55,523,14,13,Overpass (maps.mail.ru),2026-08-16T19:47:03.644917,3014,Alicante
3,5,16,1,0,Overpass (maps.mail.ru),2026-08-16T19:47:17.663266,4013,Almería
4,20,63,14,8,Overpass (maps.mail.ru),2026-08-16T19:47:31.411079,5019,Ávila