In [2]:
import os
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import seaborn as sns
from ydata_profiling import ProfileReport

En primer lugar, ejecutamos el main.py de extracción de datos, para actualizar mantener los datos actualizados

In [3]:
actualizar = input("""¿Deseas actualizar los archivos de datos? (s/n)
         Ten en cuenta que puede tardar bastante en hacer las consultas, 
         por lo que si ya has cargado los datos una vez recomiendo no volver a hacerlo: """)

if actualizar=="s":
    %run main.py
elif actualizar=="n":
    print("No se han actualizado los archivos de datos.")

No se han actualizado los archivos de datos.

In [4]:
INE_localidades = pd.read_csv('data/processed/flujo_ine_localidad.csv', sep=',', encoding='UTF-8')
f_INE_provincias = pd.read_csv('data/processed/flujo_ine_provincia.csv', sep=',', encoding='UTF-8')
INE_provincias = pd.read_csv('data/processed/INE_provincias.csv', sep=',', encoding='UTF-8')
provincias_data = pd.read_csv('data/processed/Carto_provincias.csv', sep=',', encoding='UTF-8')
OpenStreetDf = pd.read_csv('data/processed/oferta_osm.csv', sep=',', encoding='UTF-8')
localidades_data = pd.read_csv('data/processed/municipios_espana.csv', sep=',', encoding='UTF-8')
clima_df = pd.read_csv('data/processed/clima_aemet.csv', sep=',', encoding='UTF-8')

In [5]:
#INE_localidades.head()
#INE_localidades.shape --> Resultado: (6610, 11)
INE_localidades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6610 entries, 0 to 6609
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   COD                     6610 non-null   object
 1   Nombre                  6610 non-null   object
 2   T3_Unidad               6610 non-null   object
 3   T3_Escala               6610 non-null   object
 4   Fecha                   6610 non-null   object
 5   T3_Periodo              6610 non-null   object
 6   T3_TipoDato             6610 non-null   object
 7   Anyo                    6610 non-null   int64
 8   Valor                   5560 non-null   float64
 9   MetaData_json           6610 non-null   object
 10  tabla_id                6610 non-null   int64
 11  _meta.fecha_extraccion  6610 non-null   object
dtypes: float64(1), int64(2), object(9)
memory usage: 619.8+ KB

In [6]:
#localidades_data.head()
#
provincias_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   query                   52 non-null     object
 1   id                      52 non-null     int64
 2   muniCode                52 non-null     int64
 3   provinceCode            52 non-null     int64
 4   muni                    52 non-null     object
 5   province                52 non-null     object
 6   comunidadAutonoma       52 non-null     object
 7   lat                     52 non-null     float64
 8   lng                     52 non-null     float64
 9   type                    52 non-null     object
 10  state                   52 non-null     int64
 11  raw_json                52 non-null     object
 12  _meta.fecha_extraccion  52 non-null     object
dtypes: float64(2), int64(4), object(7)
memory usage: 5.4+ KB

In [7]:

f_INE_provincias.tail()

,COD,Nombre,T3_Unidad,T3_Escala,Fecha,T3_Periodo,T3_TipoDato,Anyo,Valor,MetaData_json,tabla_id,_meta.fecha_extraccion
5035,EOT1822,Melilla. Pernoctaciones. Residentes en el extr...,Pernoctaciones,,2025-12-01T00:00:00.000+01:00,M12,Provisional,2025,1844.0,"[{""Id"": 8995, ""T3_Variable"": ""Comunidades y Ci...",2074,2026-08-24T19:52:29.866208
5036,EOT1822,Melilla. Pernoctaciones. Residentes en el extr...,Pernoctaciones,,2025-11-01T00:00:00.000+01:00,M11,Provisional,2025,1479.0,"[{""Id"": 8995, ""T3_Variable"": ""Comunidades y Ci...",2074,2026-08-24T19:52:29.866208
5037,EOT1822,Melilla. Pernoctaciones. Residentes en el extr...,Pernoctaciones,,2025-10-01T00:00:00.000+02:00,M10,Provisional,2025,2448.0,"[{""Id"": 8995, ""T3_Variable"": ""Comunidades y Ci...",2074,2026-08-24T19:52:29.866208
5038,EOT1822,Melilla. Pernoctaciones. Residentes en el extr...,Pernoctaciones,,2025-09-01T00:00:00.000+02:00,M09,Provisional,2025,2077.0,"[{""Id"": 8995, ""T3_Variable"": ""Comunidades y Ci...",2074,2026-08-24T19:52:29.866208
5039,EOT1822,Melilla. Pernoctaciones. Residentes en el extr...,Pernoctaciones,,2025-08-01T00:00:00.000+02:00,M08,Provisional,2025,4788.0,"[{""Id"": 8995, ""T3_Variable"": ""Comunidades y Ci...",2074,2026-08-24T19:52:29.866208

In [8]:
INE_provincias.head()
#INE_provincias[INE_provincias['INE_EOH_PROV.indicador']=='Viajero'].head()
#INE_provincias.info()

,COD,Nombre,T3_Unidad,T3_Escala,Fecha,T3_Periodo,T3_TipoDato,Anyo,Valor,MetaData_json,tabla_id,_meta.fecha_extraccion
0,DPOP1,Total Nacional. Total. Total habitantes. Perso...,Personas,,2021-01-01T00:00:00.000+01:00,A,Definitivo,2021,47385107.0,"[{""Id"": 16473, ""T3_Variable"": ""Comunidades y C...",2852,2026-08-24T19:52:20.261921
1,DPOP2,Total Nacional. Hombres. Total habitantes. Per...,Personas,,2021-01-01T00:00:00.000+01:00,A,Definitivo,2021,23222953.0,"[{""Id"": 16473, ""T3_Variable"": ""Comunidades y C...",2852,2026-08-24T19:52:20.261921
2,DPOP3,Total Nacional. Mujeres. Total habitantes. Per...,Personas,,2021-01-01T00:00:00.000+01:00,A,Definitivo,2021,24162154.0,"[{""Id"": 16473, ""T3_Variable"": ""Comunidades y C...",2852,2026-08-24T19:52:20.261921
3,DPOP160,Albacete. Total. Total habitantes. Personas.,Personas,,2021-01-01T00:00:00.000+01:00,A,Definitivo,2021,386464.0,"[{""Id"": 3, ""T3_Variable"": ""Provincias"", ""Nombr...",2852,2026-08-24T19:52:20.261921
4,DPOP161,Albacete. Hombres. Total habitantes. Personas.,Personas,,2021-01-01T00:00:00.000+01:00,A,Definitivo,2021,193205.0,"[{""Id"": 3, ""T3_Variable"": ""Provincias"", ""Nombr...",2852,2026-08-24T19:52:20.261921

In [9]:
#provincias_data.head()
provincias_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   query                   52 non-null     object
 1   id                      52 non-null     int64
 2   muniCode                52 non-null     int64
 3   provinceCode            52 non-null     int64
 4   muni                    52 non-null     object
 5   province                52 non-null     object
 6   comunidadAutonoma       52 non-null     object
 7   lat                     52 non-null     float64
 8   lng                     52 non-null     float64
 9   type                    52 non-null     object
 10  state                   52 non-null     int64
 11  raw_json                52 non-null     object
 12  _meta.fecha_extraccion  52 non-null     object
dtypes: float64(2), int64(4), object(7)
memory usage: 5.4+ KB

In [10]:
#OpenStreetDf.head()
OpenStreetDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   query_name              52 non-null     object
 1   lat                     52 non-null     float64
 2   lon                     52 non-null     float64
 3   radio_metros            52 non-null     int64
 4   mirror_usado            52 non-null     object
 5   elements_raw_json       52 non-null     object
 6   _meta.fecha_extraccion  52 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 3.0+ KB

Cambios necesarios:
- INE_localidades y localidades_data se deben combinar
- Provincias_data se debe pivotar para tener en varias columnas los valores numéricos y sólo 52 filas
- En f_INE_provincias, INE_Provincias, Provincias_data y OpenStreetDF se deben combinar

El resultado debe ser dos DataFrames, uno para localidades, y otro para provincias. Posteriormente se deberá hacer un Left Join en las localidades para los municipios. Posteriormente, se deben combinar ambos Dfs

Comenzamos filtrando y reduciendo las columnas en localidades_data

In [11]:
# Primero, dividimos la columna de 'Nombre' usando el metodo .str.split()
columnas = ['Localidad', 'Genero', 'Metrica', 'Unidad']
localidades_data[columnas] = localidades_data['Nombre'].str.split('.', n=3, expand=True)

for col in columnas:
    localidades_data[col] = localidades_data[col].str.strip() #Eliminamos los espacios al inicio y final con un bucle

# Suprimimos las columnas que no vamos a necesitar
localidades_data.drop(columns=['Nombre', 'Fecha', 'T3_Unidad', 'T3_Escala', 'T3_Periodo', 'T3_TipoDato','Anyo', 'tabla_id', 'MetaData_json', '_meta.fecha_extraccion'],
                     inplace=True
                     )

# Como nos interesa la poblacion total por municipio, filtramos Genero == 'Total
localidades_data = localidades_data[localidades_data['Genero'] == 'Total']

# Comprobamos el resultado
localidades_data.head()

          COD   Valor Localidad Genero           Metrica     Unidad
0   DPOP19723    73.0    Ababuj  Total  Total habitantes  Personas.
3   DPOP17671   849.0    Abades  Total  Total habitantes  Personas.
6    DPOP4663   337.0    Abadía  Total  Total habitantes  Personas.
9   DPOP12721  2239.0    Abadín  Total  Total habitantes  Personas.
12  DPOP22525  7768.0   Abadiño  Total  Total habitantes  Personas.

A continuación, adaptaremos INE_localidades. En la columna T3_Unidad tenemos dos valores, Viajeros y pernoctaciones. Vamos a quedarnos con los datos completos de 2025 y excluir 2026.

In [12]:
INE_localidades.head(2) #2 para que ocupe poco espacio en la salida

,COD,Nombre,T3_Unidad,T3_Escala,Fecha,T3_Periodo,T3_TipoDato,Anyo,Valor,MetaData_json,tabla_id,_meta.fecha_extraccion
0,EOT2611,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,Viajeros,,2026-07-01T00:00:00.000+02:00,M07,Provisional,2026,18734.0,"[{""Id"": 284332, ""T3_Variable"": ""Concepto turís...",2078,2026-08-24T19:52:33.660716
1,EOT2611,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,Viajeros,,2026-06-01T00:00:00.000+02:00,M06,Provisional,2026,19464.0,"[{""Id"": 284332, ""T3_Variable"": ""Concepto turís...",2078,2026-08-24T19:52:33.660716

In [13]:


#Como el DF tiene dos en el mismo modelo, vamos a partirlo en dos y despues unir sus columnas resultantes

INE_localidades2 = INE_localidades[(~INE_localidades['Nombre'].str.startswith('Nacional'))]
columnas = ['localidad', 'metrica', 'Campos', 'Origen', 'Tipo']
INE_localidades2[columnas] = INE_localidades2['Nombre'].str.split('.', n=4, expand=True)

INE_localidades2.drop(columns=['Nombre', 'Fecha', 'T3_Escala', 'T3_TipoDato', 'tabla_id', 'MetaData_json', '_meta.fecha_extraccion', 'Tipo'],
                     inplace=True
                     )

print(INE_localidades2.nunique()) 
print('-----------------------------')
print(INE_localidades2.Anyo.value_counts()) #Decidimos quedarnos con el año 2026
print('-----------------------------')
print(INE_localidades2.metrica.value_counts()) #Solo nos interesa mantener viajeros y pernoctaciones (Total categorias es el total)
print('-----------------------------')
print(INE_localidades2.Origen.value_counts()) #Nos interesa diferenciar el origen en dos columnas, pero cambiando los nombres
print('-----------------------------')

INE_localidades2 = (INE_localidades2[(INE_localidades2['Anyo'] == 2026) &
                                     (INE_localidades2['metrica'] != ' Total categorías')]
                    .rename(columns= {'T3_Periodo': 'periodo'}) # Renombramos la columna para su posterior uso
                    )

INE_localidades2['Origen'] = (INE_localidades2['Origen']
                              .str.strip() #Para limpiar el texto, ya que .replace solo no daba resultado
                              .replace({'Residentes en España': 'Nacional',
                                        'Residentes en el Extranjero': 'Extranjero'}))


INE_localidades2 =(INE_localidades2.sort_values('Valor', ascending=False)
 .pivot_table(index= 'localidad',
                             columns= ['metrica', 'Origen'],
                             values= ['Valor', 'periodo'],
                             aggfunc= {'Valor': 'sum', 'periodo': 'first'})
 .reset_index())

INE_localidades2.columns = INE_localidades2.columns.map(' '.join) #join con valor vacio porque ya existe un valor vacio en las metricas

print('Resultado del Dataframe')
INE_localidades2.head(3)

COD            164
T3_Unidad        2
T3_Periodo      12
Anyo             2
Valor         1350
localidad       40
metrica          3
Campos           4
Origen           2
dtype: int64
-----------------------------
Anyo
2026    1142
2025     812
Name: count, dtype: int64
-----------------------------
metrica
Viajero             905
Pernoctaciones      905
Total categorías    144
Name: count, dtype: int64
-----------------------------
Origen
Residentes en España           978
Residentes en el Extranjero    976
Name: count, dtype: int64
-----------------------------
Resultado del Dataframe

,localidad,Valor Pernoctaciones Extranjero,Valor Pernoctaciones Nacional,Valor Viajero Extranjero,Valor Viajero Nacional,periodo Pernoctaciones Extranjero,periodo Pernoctaciones Nacional,periodo Viajero Extranjero,periodo Viajero Nacional
0,Alcalá de Henares,105923.0,173758.0,48323.0,105270.0,M04,M05,M04,M05
1,Alcúdia,2053063.0,111390.0,337501.0,23966.0,M07,M05,M07,M05
2,Almuñécar,179775.0,212991.0,30139.0,74891.0,M05,M07,M05,M07

In [14]:

# Ahora, repetimos con la otra parte del dataframe
INE_localidades_nac = INE_localidades[INE_localidades['Nombre'].str.startswith('Nacional')]

# Misma operación con la otra metrica, pero diferencia en las columnas que desagregamos
columnas= ['tipo', 'metrica', 'localidad', 'tipo residente']

INE_localidades_nac[columnas] = INE_localidades_nac['Nombre'].str.split('.', n=3, expand=True)

INE_localidades_nac.drop(columns=['Nombre', 'Fecha', 'T3_Escala', 'T3_TipoDato','tipo', 'tabla_id', 'MetaData_json', '_meta.fecha_extraccion'],
                     inplace=True
                        )

# Revisamos un poco los valores que nos encontramos
print(INE_localidades_nac.nunique()) 
print('-----------------------------')
print(INE_localidades_nac.metrica.value_counts()) #Otra vez, elegimos 2026
print('-----------------------------')
print(INE_localidades_nac['tipo residente'].value_counts()) #Genera un problema, ya que algunas filas no presentan bien si es español o extranjero

#Primero, solucionaremos el problema de tipo residente, apoyandonos en numpy

condiciones = [INE_localidades_nac['tipo residente'].str.contains('España', case=False, na = False),
               INE_localidades_nac['tipo residente'].str.contains('extranjero', case=False, na = False)
               ]
eleccion = ['Nacional', 'Extranjero']

INE_localidades_nac['tipo turista'] = np.select(condiciones, eleccion, default= ' ')

# Modificamos el DF
INE_localidades_nac = (INE_localidades_nac[(INE_localidades_nac['Anyo'] == 2026) & #Nos quedamos con 2026 porque tiene más metricas
                                           (INE_localidades_nac['metrica'] != ' Establecimientos hoteleros')
                                           ] 
                       .rename(columns={'T3_Periodo': 'periodo'}) #Aprovechamos para renombrar esta columna
                       )                 

# metodo rapido para modificar valor, ya que será necesario en el siguiente
INE_localidades_nac.loc[INE_localidades_nac['metrica'].str.strip() == 'Viajeros', 'metrica'] = 'Viajero'

# Para lograr tener el mes de mayor valor en la pivotacion, primero ordenaremos para poder mantener el mes con mayor numero de viajeros
INE_localidades_nac = (INE_localidades_nac
                       .sort_values('Valor', ascending=False) #Ordenamos
                       .pivot_table(index=['localidad'],
                                    columns= ['metrica', 'tipo turista'],
                                    values= ['Valor','periodo'],
                                    aggfunc= {'Valor':'sum', 'periodo':'first'}) #Pivotamos
                       .reset_index()
                       )

# Eliminamos bandas y unificamos en el nombre de columna
INE_localidades_nac.columns = INE_localidades_nac.columns.map(' '.join) #join con valor vacio porque ya existe un valor vacio en las metricas

print('-----------------------------')
print('Resultado del Dataframe:')
INE_localidades_nac.head(3)

COD                388
T3_Unidad            2
T3_Periodo          12
Anyo                 2
Valor             4077
metrica              3
localidad           74
tipo residente      52
dtype: int64
-----------------------------
metrica
Viajeros                      1728
Pernoctaciones                1728
Establecimientos hoteleros    1200
Name: count, dtype: int64
-----------------------------
tipo residente
Residentes en España.                                             1728
Residentes en el extranjero.                                      1728
03063-Denia. Residentes en España.                                  24
03063-Denia. Residentes en el extranjero.                           24
04066-Níjar. Residentes en España.                                  24
04066-Níjar. Residentes en el extranjero.                           24
07014-Capdepera. Residentes en España.                              24
07014-Capdepera. Residentes en el extranjero.                       24
07051-Sant Llorenç des Cardassar. Residentes en España.             24
07051-Sant Llorenç des Cardassar. Residentes en el extranjero.      24
10148-Plasencia. Residentes en España.                              24
10148-Plasencia. Residentes en el extranjero.                       24
10195-Trujillo. Residentes en España.                               24
10195-Trujillo. Residentes en el extranjero.                        24
12089-Peñiscola. Residentes en España.                              24
12089-Peñiscola. Residentes en el extranjero.                       24
17095-Lloret de Mar. Residentes en España.                          24
17095-Lloret de Mar. Residentes en el extranjero.                   24
22054-Benasque. Residentes en España.                               24
22054-Benasque. Residentes en el extranjero.                        24
22130-Jaca. Residentes en España.                                   24
22130-Jaca. Residentes en el extranjero.                            24
22204-Sallent de Gállego. Residentes en España.                     24
22204-Sallent de Gállego. Residentes en el extranjero.              24
23028-Cazorla. Residentes en España.                                24
23028-Cazorla. Residentes en el extranjero.                         24
25025-Naut Arant. Residentes en España.                             24
25025-Naut Arant. Residentes en el extranjero.                      24
25243-Vielha e Mijaran. Residentes en España.                       24
25243-Vielha e Mijaran. Residentes en el extranjero.                24
27066-Viveiro. Residentes en España.                                24
27066-Viveiro. Residentes en el extranjero.                         24
29051-Estepona. Residentes en España.                               24
29051-Estepona. Residentes en el extranjero.                        24
32054-Ourense. Residentes en España.                                24
32054-Ourense. Residentes en el extranjero.                         24
33012-Cangas de Onís. Residentes en España.                         24
33012-Cangas de Onís. Residentes en el extranjero.                  24
33076-Villaviciosa. Residentes en España.                           24
33076-Villaviciosa. Residentes en el extranjero.                    24
34120-Palencia. Residentes en España.                               24
34120-Palencia. Residentes en el extranjero.                        24
36022-Grove (O). Residentes en España.                              24
36022-Grove (O). Residentes en el extranjero.                       24
36051-Sanxenxo. Residentes en España.                               24
36051-Sanxenxo. Residentes en el extranjero.                        24
43038-Cambrils. Residentes en España.                               24
43038-Cambrils. Residentes en el extranjero.                        24
43905-Salou. Residentes en España.                                  24
43905-Salou. Residentes en el extranjero.                           24
49021-Benavente. Residentes en España.                              24
49021-Benavente. Residentes en el extranjero.                       24
Name: count, dtype: int64
-----------------------------
Resultado del Dataframe:

,localidad,Valor Pernoctaciones Extranjero,Valor Pernoctaciones Nacional,Valor Viajero Extranjero,Valor Viajero Nacional,periodo Pernoctaciones Extranjero,periodo Pernoctaciones Nacional,periodo Viajero Extranjero,periodo Viajero Nacional
0,Adeje,6069924.0,302222.0,859460.0,76113.0,M07,M07,M03,M07
1,Albacete,32020.0,171794.0,16601.0,111280.0,M02,M05,M04,M05
2,Albarracín,6936.0,37844.0,4255.0,20366.0,M05,M04,M03,M04

Antes de concatenar de vuelta los dos dataframes, debemos solucionar la diferencia entre las columnas resultado las operaciones paralelas

In [15]:
#Unificados nombres de columnas
columnas = (INE_localidades_nac.columns
            .str.strip() #Eliminamos espacios al inicio y final
            .str.replace('  ', ' ', regex= False) # suprimimos dobles espaciados
            .str.upper() #Normalizamos todas las columnas a mayusculas
            )
# Aplicamos
INE_localidades2.columns = columnas
INE_localidades_nac.columns = columnas

# Unimos los Dfs
INE_localidades = pd.concat([INE_localidades2, INE_localidades_nac], ignore_index=True)

# Filtramos para suprimir que no tienen valores
INE_localidades = INE_localidades[INE_localidades[INE_localidades.columns[1]] > 0]

# Comprobamos si hay algun duplicado
print(INE_localidades.value_counts('LOCALIDAD').sort_values(ascending=False).head(5)) 

# Revisamos
INE_localidades.sort_values('LOCALIDAD').head()

LOCALIDAD
Adeje         1
Albacete      1
Albarracín    1
Algeciras     1
Alicante      1
Name: count, dtype: int64

,LOCALIDAD,VALOR PERNOCTACIONES EXTRANJERO,VALOR PERNOCTACIONES NACIONAL,VALOR VIAJERO EXTRANJERO,VALOR VIAJERO NACIONAL,PERIODO PERNOCTACIONES EXTRANJERO,PERIODO PERNOCTACIONES NACIONAL,PERIODO VIAJERO EXTRANJERO,PERIODO VIAJERO NACIONAL
38,Adeje,6069924.0,302222.0,859460.0,76113.0,M07,M07,M03,M07
39,Albacete,32020.0,171794.0,16601.0,111280.0,M02,M05,M04,M05
40,Albarracín,6936.0,37844.0,4255.0,20366.0,M05,M04,M03,M04
41,Algeciras,73041.0,88538.0,43367.0,43260.0,M07,M03,M03,M03
42,Alicante,1063874.0,367537.0,360259.0,181608.0,M07,M06,M05,M06

Pasando a los datos agregados por provincias, el flujo de transformaciones será similar a los dfs de localidades, con pequeñas variaciones

In [ ]:
f_INE_provincias2 =f_INE_provincias.copy()

print(f_INE_provincias2.nunique())
print('-----------------------------')
print(f_INE_provincias2['T3_Unidad'].value_counts())
print('-----------------------------')
print(f_INE_provincias2.Nombre.value_counts())

#NOTA: en este DF están mezcladas provincias, comunidades y total nacional, conviene quedarse solo con provincias
# Para quedarnos con Provincias, se debe filtrar en la columna MetaData_json, que contiene el valor crudo en formato json, aunque no es necesario desagregarlo

f_INE_provincias2 = f_INE_provincias2[f_INE_provincias2['MetaData_json'].str.contains('Provincia', case=False, na=False)]

columnas=['Provincia', 'metrica', 'Origen']

f_INE_provincias2[columnas] = f_INE_provincias2['Nombre'].str.split('.', n=2, expand=True)
f_INE_provincias2 = f_INE_provincias2.drop(columns= ['Nombre', 'T3_Escala', 'Fecha', 'T3_TipoDato', 'MetaData_json', 'tabla_id', '_meta.fecha_extraccion'])


#Filtramos años. En este caso nos quedamos con 2025 ya que contiene los doce meses
f_INE_provincias2 = (f_INE_provincias2[f_INE_provincias2['Anyo'] == 2025]
                     .rename(columns={'T3_Periodo': 'periodo'}))



f_INE_provincias2 = f_INE_provincias2.pivot_table(index=['Provincia'],
                                    columns= ['metrica'],
                                    values= ['Valor','periodo'],
                                    aggfunc= {'Valor':'sum', 'periodo':'first'})

f_INE_provincias2.columns = f_INE_provincias2.columns.map(' '.join)
f_INE_provincias2 = (f_INE_provincias2.columns
            .str.strip() #Eliminamos espacios al inicio y final
            .str.replace('  ', ' ', regex= False) # suprimimos dobles espaciados
            .str.upper() #Normalizamos todas las columnas a mayusculas
            )

f_INE_provincias2 #CAMBIAR VIAJERO POR VIAJEROS O AL REVES

COD                        420
Nombre                     420
T3_Unidad                    2
T3_Escala                    1
Fecha                       12
T3_Periodo                  12
T3_TipoDato                  1
Anyo                         2
Valor                     4504
MetaData_json              420
tabla_id                     1
_meta.fecha_extraccion       1
dtype: int64
-----------------------------
T3_Unidad
Viajeros          2520
Pernoctaciones    2520
Name: count, dtype: int64
-----------------------------
Nombre
Nacional. Viajeros. Total categorías. Total.                          12
Nacional. Viajeros. Total categorías. Residentes en España.           12
Nacional. Viajeros. Total categorías. Residentes en el extranjero.    12
Nacional. Pernoctaciones. Total categorías. Total.                    12
Nacional. Pernoctaciones. Total categorías. Residentes en España.     12
                                                                      ..
Melilla. Viajeros. Residentes en España.                              12
Melilla. Viajeros. Residentes en el extranjero.                       12
Melilla. Pernoctaciones. Total.                                       12
Melilla. Pernoctaciones. Residentes en España.                        12
Melilla. Pernoctaciones. Residentes en el extranjero.                 12
Name: count, Length: 420, dtype: int64

Index(['VALOR PERNOCTACIONES', 'VALOR VIAJERO', 'VALOR VIAJEROS',
       'PERIODO PERNOCTACIONES', 'PERIODO VIAJERO', 'PERIODO VIAJEROS'],
      dtype='object')